### ISSUE TITLE
Add Zwave Support

### ISSUE THREAD

**Issue by NickWaterton** [mjcumming/ISY-Homie-Bridge#2]
Hi, I'm trying out your bridge.
Seems to work well for insteon device nodes.

What needs to be done to support zwave nodes?

I am getting this error:
```
2020-02-05 12:44:11,650 - isy994.controller - ERROR - Event handler Error 'Device_ZWave_Power' object has no attribute 'get_homie_device_id'
Traceback (most recent call last):
  File "/home/nick/Scripts/ISY994v5/isy994/controller.py", line 163, in publish_container_event
    self.event_handler(container, item, event, *args)
  File "/home/nick/Scripts/ISY-Homie-Bridge/isy_homie/bridge.py", line 88, in _isy_event_handler
    self._device_event_handler(item, event, args)
  File "/home/nick/Scripts/ISY-Homie-Bridge/isy_homie/bridge.py", line 116, in _device_event_handler
    self.homie_devices[device.get_homie_device_id()] = device
AttributeError: 'Device_ZWave_Power' object has no attribute 'get_homie_device_id'
```

I'm currently using `Py-ISY` with my own `MQTT-ISY` bridge (python), and I'm able to control my zwave nodes without too much problem, but I'm just passing generic events/values back and forth, (and hand coding the channels in Openhab MQTT).

Do you need a specific `device.py` for each node type? (which could get out of hand with zwave).

I was hoping that your bridge would save me a lot of typing...

**Comment by NickWaterton** [comment]
Digging a bit further, this is caused by:
```
2020-02-05 12:50:57,870 - isy994.controller - ERROR - Event handler Error Invalid device id switch-zw003_1
Traceback (most recent call last):
  File "/home/nick/Scripts/ISY994v5/isy994/controller.py", line 163, in publish_container_event
    self.event_handler(container, item, event, *args)
  File "/home/nick/Scripts/ISY-Homie-Bridge/isy_homie/bridge.py", line 88, in _isy_event_handler
    self._device_event_handler(item, event, args)
  File "/home/nick/Scripts/ISY-Homie-Bridge/isy_homie/bridge.py", line 102, in _device_event_handler
    device = Switch(device, self.homie_settings, self.mqtt_settings)
  File "/home/nick/Scripts/ISY-Homie-Bridge/isy_homie/devices/switch.py", line 19, in __init__
    mqtt_settings,
  File "/usr/local/lib/python3.6/dist-packages/Homie4-0.2.7-py3.6.egg/homie/device_switch.py", line 14, in __init__
    super().__init__(device_id, name, homie_settings, mqtt_settings)
  File "/usr/local/lib/python3.6/dist-packages/Homie4-0.2.7-py3.6.egg/homie/device_base.py", line 71, in __init__
    assert validate_id(device_id), "Invalid device id {}".format(device_id)
AssertionError: Invalid device id switch-zw003_1
```

Which is caused by the "_" in the node id.

**Comment by NickWaterton** [comment]
So I got rid of the errors with a couple of changes:
in `devices\base.py`
I changed `get_homie_device_id()` to:
```
def get_homie_device_id(self):
        # return re.sub(r'\W+', '', self.isy_device.name.lower())
        return self.isy_device.get_identifier().replace(" ", "").replace("_", "").lower()
```
To get rid of the problematic "_".

Then in `bridge.py` I changed `_device_event_handler()` to handle (ignore) "power" (and any other unsupported) devices
```
    def _device_event_handler(self, device, event, *args):
        logger.debug("Device event {}".format(device.name, event, args))
        if event == "add":
            if device.device_type == "switch":
                device = Switch(device, self.homie_settings, self.mqtt_settings)
            elif device.device_type == "dimmer":
                device = Dimmer(device, self.homie_settings, self.mqtt_settings)
            elif device.device_type == "fan":
                device = Fan(device, self.homie_settings, self.mqtt_settings)
            elif device.device_type == "contact":
                device = Contact(device, self.homie_settings, self.mqtt_settings)
            elif device.device_type == "thermostat":
                device = Thermostat(device, self.homie_settings, self.mqtt_settings)
            elif device.device_type == "power":
                logger.warning("Device type power not yet supported for {}'".format(device.name))
                return
            elif device.device_type == "controller":
                device = Controller_Action(
                    device, self.homie_settings, self.mqtt_settings
                )
            else:
                logger.warning("Device type not found for {}".format(device.name, device.device_type))
                return

            self.homie_devices[device.get_homie_device_id()] = device
```
So, now I get no more errors.

Having said that, and followed the code arround, it looks like supporting the many types of zwave devices will be a huge task...

**Comment by mjcumming** [comment]
Hi Nick

It shouldn't be hard to add zWave devices that share common functionality. Ie. for Insteon devices there is just one device file for all the dimmer devices even though there are several variants.

Would prefer to discuss ISY994v5 and adding zWave support on that GitHub page rather than here.

I will add the fix to the device id.

**Comment by NickWaterton** [comment]
Having just tested it, a zwave outlet added just fine (as a switch), and I can turn it on and off, don't get the power monitoring features (as expected), but control/feedback isn't a problem.

Wasn't sure where to put this, as ISY994v5 and ISY-Bridge are closely related.

Thanks for the quick response.

**Comment by mjcumming** [comment]
Prefer to keep mqtt/homie issues here, direct isy994 issues in that module. I'll close this thread and we can talk about getting more zWave devices added over there.
